"use client";

import { Layers } from "lucide-react";
import { cn } from "~/lib/utils";

// ─── Types ───────────────────────────────────────────────────────────

interface ContextHeaderProps {
  name: string;
  snapshot: string;
  unitCount: number;
  perspectiveCount: number;
  className?: string;
}

// ─── Skeleton ────────────────────────────────────────────────────────

export function ContextHeaderSkeleton({ className }: { className?: string }) {
  return (
    <div
      className={cn("space-y-3 rounded-card border border-border bg-bg-primary p-space-4", className)}
      aria-busy="true"
      aria-label="Loading context header"
    >
      <div className="animate-pulse space-y-3">
        <div className="flex items-center gap-space-2">
          <div className="h-5 w-5 rounded bg-bg-secondary" />
          <div className="h-5 w-40 rounded bg-bg-secondary" />
        </div>
        <div className="h-4 w-full rounded bg-bg-secondary" />
        <div className="flex gap-space-4">
          <div className="h-3 w-20 rounded bg-bg-secondary" />
          <div className="h-3 w-24 rounded bg-bg-secondary" />
        </div>
      </div>
    </div>
  );
}

// ─── Component ───────────────────────────────────────────────────────

export function ContextHeader({
  name,
  snapshot,
  unitCount,
  perspectiveCount,
  className,
}: ContextHeaderProps) {
  const hasSnapshot = snapshot.trim().length > 0;

  return (
    <section
      aria-label={`Context: ${name}`}
      className={cn(
        "rounded-card border border-border bg-bg-primary p-space-4 space-y-2",
        className,
      )}
    >
      {/* Context name */}
      <div className="flex items-center gap-space-2">
        <Layers className="h-5 w-5 text-text-tertiary" aria-hidden="true" />
        <h2 className="font-heading text-lg font-semibold text-text-primary">
          {name}
        </h2>
      </div>

      {/* Snapshot summary */}
      <p
        className={cn(
          "text-sm leading-relaxed",
          hasSnapshot
            ? "text-text-secondary italic"
            : "text-text-tertiary italic",
        )}
      >
        {hasSnapshot
          ? snapshot
          : "Context summary will be generated by AI"}
      </p>

      {/* Counts */}
      <div className="flex items-center gap-space-4 text-xs text-text-tertiary">
        <span>
          {unitCount} {unitCount === 1 ? "unit" : "units"}
        </span>
        <span>
          {perspectiveCount} {perspectiveCount === 1 ? "perspective" : "perspectives"}
        </span>
      </div>
    </section>
  );
}
